name:                wasted-time
version:             0.1.0.0
github:              "jecaro/wasted-time"
license:             BSD3
author:              "Jean-Charles Quillet"
maintainer:          "jeancharles.quillet@gmail.com"
copyright:           "2021 Jean-Charles Quillet"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wasted-time#readme>

dependencies:
- name: base
  mixin:
    - hiding (Prelude)
- name: relude
  mixin:
    - (Relude as Prelude)

library:
  source-dirs: src

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints

executables:
  wasted-time-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - wasted-time

tests:
  wasted-time-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - wasted-time
